package com.miaoyu.ticket.agent.domain.plan;

/** 计划校验对调用方稳定暴露的内部问题码。 */
public enum PlanValidationIssueCode {
    PLAN_ID_REQUIRED,
    PLAN_VERSION_INVALID,
    NODE_LIMIT_EXCEEDED,
    NODE_REQUIRED,
    NODE_ID_REQUIRED,
    NODE_ID_DUPLICATE,
    NODE_TYPE_REQUIRED,
    NODE_FIELD_REQUIRED,
    DEPENDENCY_INVALID,
    DEPENDENCY_CYCLE,
    INPUT_REFERENCE_INVALID,
    INPUT_REFERENCE_NOT_UPSTREAM,
    INPUT_TYPE_MISMATCH,
    TOOL_NOT_FOUND,
    TOOL_INPUT_UNKNOWN,
    TOOL_REQUIRED_INPUT_MISSING,
    WRITE_TOOL_NOT_SUPPORTED,
    WRITE_TOOL_CONFIRMATION_REQUIRED
}
